"use client";

import { useLanguage } from "@/components/LanguageProvider";

const messages: Record<string, string> = {
  "轻量 CMS 后台": "Content management",
  "后台概览": "Dashboard",
  "首页管理": "Homepage",
  "产品管理": "Products",
  "新闻管理": "News",
  "资讯信息管理": "Resources",
  "关于我们管理": "About us",
  "联系我们管理": "Contact us",
  "询价管理": "Inquiries",
  "返回前台": "View website",
  "后台登录": "Admin sign in",
  "管理员邮箱": "Admin email",
  "管理员密码": "Admin password",
  "登录中...": "Signing in...",
  "进入后台": "Sign in",
  "账号或密码错误": "Incorrect email or password",
  "退出登录": "Sign out",
  "字体": "Font",
  "字号": "Font size",
  "雅黑": "Arial / Microsoft YaHei",
  "宋体": "SimSun",
  "楷体": "KaiTi",
  "黑体": "SimHei",
  "小号": "Small",
  "正文": "Body",
  "中号": "Medium",
  "大号": "Large",
  "标题": "Heading",
  "左": "Left",
  "中": "Center",
  "右": "Right",
  "图片": "Image",
  "图片宽度": "Image width",
  "例如 300px": "For example, 300px",
  "自定义图片宽度": "Custom image width",
  "富文本工具栏": "Rich text toolbar",
  "图片上传中...": "Uploading image...",
  "图片上传失败": "Image upload failed",
  "图片已插入，请保存内容。点击图片可调整宽度。": "Image inserted. Save your content. Select the image to adjust its width.",
  "保存": "Save",
  "保存全部": "Save all",
  "删除": "Delete",
  "新增": "Add",
  "已发布": "Published",
  "草稿": "Draft",
  "已删除": "Deleted",
  "新闻": "News",
  "资讯": "Resources",
  "新新闻": "New news article",
  "新资讯": "New resource",
  "未命名新闻": "Untitled news article",
  "未命名资讯": "Untitled resource",
  "新增第一篇新闻": "Add your first news article",
  "新增第一条资讯": "Add your first resource",
  "标题 *": "Title *",
  "链接 slug *": "URL slug *",
  "分类": "Category",
  "发布日期": "Publication date",
  "阅读量": "Views",
  "作者": "Author",
  "来源": "Source",
  "封面图片": "Cover image",
  "摘要 *": "Summary *",
  "正文 *": "Content *",
  "上传后自动生成图片地址": "Upload an image or enter its URL",
  "封面上传中...": "Uploading cover...",
  "新闻封面预览": "News cover preview",
  "资讯封面预览": "Resource cover preview",
  "新闻图片": "News image",
  "资讯图片": "Resource image",
  "发布到前台新闻中心": "Publish the Chinese version in the news center",
  "发布到前台资讯信息页": "Publish the Chinese version in resources",
  "标题不能为空": "Title is required",
  "链接 slug 不能为空": "URL slug is required",
  "摘要不能为空": "Summary is required",
  "正文不能为空": "Content is required",
  "分类不能为空": "Category is required",
  "请先修正表单错误": "Please correct the form errors",
  "新闻内容已保存": "News saved",
  "资讯内容已保存": "Resources saved",
  "保存失败，请重新登录后台或检查 Supabase 配置": "Save failed. Sign in again or check the storage configuration.",
  "封面图片已上传，请保存全部新闻": "Cover uploaded. Save all news to apply.",
  "封面图片已上传，请保存全部资讯": "Cover uploaded. Save all resources to apply.",
  "资讯分类 *": "Resource category *",
  "选择或输入资讯分类": "Choose or enter a resource category",
  "新增资讯类别": "New resource category",
  "添加并应用": "Add and apply",
  "状态": "Status",
  "产品编号": "Catalog number",
  "中文名": "Chinese name",
  "英文名": "English name",
  "产品分类": "Product category",
  "CAS 号": "CAS number",
  "分子式": "Molecular formula",
  "分子量": "Molecular weight",
  "纯度": "Purity",
  "包装": "Pack size",
  "货期": "Lead time",
  "价格": "Price",
  "库存": "Stock",
  "品牌": "Brand",
  "同义词": "Synonyms",
  "标签": "Tags",
  "基本信息": "Details",
  "参考文献": "References",
  "质检证书": "Certificate",
  "规模说明": "Scale information",
  "删除时间": "Deleted at",
  "已创建草稿产品，请填写信息后保存至草稿或发布产品。": "Draft created. Complete the details, then save as a draft or publish.",
  "当前产品已移入已删除": "Product moved to deleted",
  "请先选择要删除的产品。": "Select the products to delete first.",
  "已恢复为草稿": "Restored as a draft",
  "已保存产品数据": "Products saved",
  "已保存至草稿": "Saved as a draft",
  "产品已发布": "Product published",
  "图片已上传。点击保存至草稿或发布产品后生效。": "Image uploaded. Save as a draft or publish to apply.",
  "表格文件没有可导入的数据": "The spreadsheet contains no importable data",
  "没有识别到可导入的产品。请确认表头包含产品编号、中文名、英文名、CAS 等字段。": "No products found. Check that the headers include catalog number, Chinese name, English name, or CAS.",
  "表格解析失败，请上传 .xlsx、.xls 或 .csv 文件。": "Unable to read this spreadsheet. Upload an .xlsx, .xls, or .csv file.",
  "产品详情": "Product details",
  "新产品": "New product",
  "返回产品列表": "Back to products",
  "恢复为草稿": "Restore as draft",
  "保存至草稿": "Save as draft",
  "发布产品": "Publish product",
  "选择或输入产品分类": "Choose or enter a product category",
  "新增类别名称": "New category name",
  "产品图片": "Product image",
  "产品图片预览": "Product image preview",
  "英文名 *": "English name *",
  "产品编号 *": "Catalog number *",
  "记录 ID": "Record ID",
  "多个标签用逗号分隔": "Separate tags with commas",
  "以表格方式查看全部产品，点击详情进入单个产品表单。": "Browse products in the table. Open Details to edit a product.",
  "添加产品": "Add product",
  "批量上传": "Bulk upload",
  "删除选中": "Delete selected",
  "产品状态筛选": "Filter by product status",
  "还没有产品": "No products yet",
  "点击“添加产品”创建单个产品，或点击“批量上传”导入 Excel 表格。": "Choose Add product to create one product, or Bulk upload to import a spreadsheet.",
  "当前分类没有产品": "No products in this view",
  "可以切换上方状态，或添加/批量上传新的产品。": "Choose another status, add a product, or import a spreadsheet.",
  "选择全部产品": "Select all products",
  "操作": "Actions",
  "详情": "Details",
  "询价记录已保存": "Inquiries saved",
  "询价已标记为已处理": "Inquiry marked as processed",
  "只显示待处理询价": "Show pending inquiries only",
  "暂无待处理询价记录。": "No pending inquiries.",
  "暂无询价记录。": "No inquiries yet.",
  "询价单": "Inquiries",
  "未填写联系人": "No contact name",
  "未填写公司": "No company provided",
  "询价详情": "Inquiry details",
  "标记已处理": "Mark as processed",
  "处理状态": "Status",
  "联系人": "Contact",
  "公司": "Company",
  "电话": "Phone",
  "邮箱": "Email",
  "地区": "Region",
  "客户备注": "Customer notes",
  "销售备注": "Sales notes",
  "未填写": "Not provided",
  "产品清单": "Products",
  "产品": "Product",
  "CAS / 货号": "CAS / Catalog number",
  "规格": "Pack size",
  "数量": "Quantity",
  "待确认": "To be confirmed",
  "待处理": "Pending",
  "已报价": "Quoted",
  "已关闭": "Closed",
  "已处理": "Processed"
};

export function useAdminLanguage() {
  const { locale } = useLanguage();
  return { locale, t: (text: string) => locale === "en" ? messages[text] || text : text };
}

export async function contentErrorMessage(response: Response, fallback: string) {
  try {
    const payload = await response.json() as { error?: string; message?: string };
    return payload.error || payload.message || fallback;
  } catch { return fallback; }
}
